import pandas as pd
import streamlit as st

# 1. Page Configuration
st.set_page_config(
    page_title="Laptop Ledger", page_icon="💻", layout="wide"
)

# 2. Read the HTML Template and CSV Data
try:
    with open("laptop_ledger.html", "r", encoding="utf-8") as f:
        html_template = f.read()
    
    # Load your CSV data generated by your scraper/merger
    df = pd.read_csv("master_laptops.csv")
    
    # Convert dataframe rows into a JSON string so JavaScript inside your HTML can read it instantly
    data_json = df.to_json(orient="records")

    # Inject the CSV data directly into a JavaScript variable inside your HTML template
    # This replaces the need to manually drag-and-drop the CSV file every time!
    injected_html = html_template.replace(
        "let allRows = [];", 
        f"let allRows = {data_json}; dropzone.style.display = 'none'; appArea.style.display = 'block'; sidebar.classList.add('visible'); ticker.style.display = 'flex'; fileToolbar.style.display = 'flex'; updateStats(); render();"
    )

    # 3. Render the fully loaded HTML app natively using HTML components with full height
    st.components.v1.html(injected_html, height=1200, scrolling=True)

except FileNotFoundError as e:
    st.error(f"⚠️ Missing file: {e}. Make sure `laptop_ledger.html` and `master_laptops.csv` are in your folder.")